### PR TITLE
2015-04-28 Java Collections

### PR DESCRIPTION
**Pull request by aewhite**
Next blog post @addamh @kennycason please review. 

@addamh, is the dist folder supposed to be in git?

### CODE REVIEW

**Comment by aewhite** [comment]
PR updates made. I am holding off until @addamh reviews, in particular the "dist" question.

**Comment by addamh** [comment]
Yeah cause after committing the files to master, the deploy task does a git subtree push that pushes the contents of dist to another branch which github hosts the files from

**Comment by aewhite** [comment]
I'm having problems fully parsing that comment. So, to be clear it's good to go?

**Comment by addamh** [comment]
yep good to go

**Pull request merged**
